/**
 * Generates a minimal, deterministic aiXml representation of a question
 * from the fields already available (no extra AI calls required).
 *
 * This is used for P2 policy: every imported question must have an aiXml
 * field even when a full DCE-quality XML is not generated by the AI.
 *
 * The resulting XML follows the same structure as the one produced by the
 * generate-question-flow prompt so that downstream consumers (explanations,
 * audit tools) can parse it uniformly.
 */

export interface MinimalQuestionFields {
  subjectId?: string;
  componentId?: string;
  competencyId?: string;
  level?: string;
  text?: string;
  options?: string[];
  correctAnswerIndex?: number;
  explanation?: string;
}

/** Escapes characters that are special inside XML text nodes. */
function escapeXml(value: unknown): string {
  const str = value == null ? '' : String(value);
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * Produces a minimal aiXml string from the given question fields.
 * The XML follows the AIXML 2.0 structure used by the generate-question-flow
 * so that downstream consumers (explanations, audit tools) can parse it uniformly.
 * The XML is deterministic: same inputs always produce the same output.
 */
export function generateMinimalAiXml(q: MinimalQuestionFields): string {
  const subjectId = escapeXml(q.subjectId ?? '');
  const level = escapeXml(q.level ?? '');
  const competencyId = escapeXml(q.competencyId ?? '');
  const componentId = escapeXml(q.componentId ?? '');
  const text = escapeXml(q.text ?? '');
  const explanation = escapeXml(q.explanation ?? '');

  const options = Array.isArray(q.options) ? q.options : [];
  const correctIdx = typeof q.correctAnswerIndex === 'number' ? q.correctAnswerIndex : -1;
  const optionLetters = ['A', 'B', 'C', 'D'];

  const optionLines = options
    .map((opt, i) => {
      const isCorrect = i === correctIdx ? 'true' : 'false';
      const letter = optionLetters[i] ?? String(i + 1);
      return `      <opcion id="${letter}" correcta="${isCorrect}">${escapeXml(opt)}</opcion>`;
    })
    .join('\n');

  return [
    `<item_icfes>`,
    `  <metadatos_psicometricos>`,
    `    <area>${subjectId}</area>`,
    `    <dificultad_esperada>${level}</dificultad_esperada>`,
    `    <origen>Importada de PDF</origen>`,
    `  </metadatos_psicometricos>`,
    `  <diseno_centrado_evidencias>`,
    `    <competencia>${competencyId}</competencia>`,
    `    <componente>${componentId}</componente>`,
    `    <afirmacion></afirmacion>`,
    `    <evidencia></evidencia>`,
    `  </diseno_centrado_evidencias>`,
    `  <cuerpo_pregunta>`,
    `    <enunciado>${text}</enunciado>`,
    `    <opciones_respuesta>`,
    optionLines,
    `    </opciones_respuesta>`,
    `  </cuerpo_pregunta>`,
    `  <analisis_didactico>`,
    `    <solucion_paso_a_paso>`,
    `      <justificacion_pedagogica>${explanation}</justificacion_pedagogica>`,
    `    </solucion_paso_a_paso>`,
    `  </analisis_didactico>`,
    `</item_icfes>`,
  ].join('\n');
}
